<a href="https://colab.research.google.com/github/AiWriter404/AI-With-Python-Digiskills/blob/main/AI_With_Python_Digiskills_W3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Topic 48
# What is Data and why its important

In [2]:
# Topic 49
# Introduction of Numpy Seabor and Matplotlib

In [3]:
# Topic 50
# Why Numpy & Enviroment Setup
# pip install numpy
import numpy as np
import time

In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape) # (2,3)
print(arr.ndim)  # 2
print(arr.dtype) # int64 (or Platform dependent)


(2, 3)
2
int64


In [5]:
py_list=list(range(1_000_000))
py_result=[]
start_time=time.time()
for i in py_list:
   py_result.append(i+5)
end_time=time.time()
print("Python List Time:", end_time-start_time)

Python List Time: 0.1218099594116211


In [6]:
np_array=np.arange(1_000_000)
start_time=time.time()
np_result=np_array+5
end_time=time.time()
print("Numpy Array Time:", end_time-start_time)

Numpy Array Time: 0.0038733482360839844


In [7]:
# Topic 51
import numpy as np
arr=np.array([1,2,3])
print(arr)


[1 2 3]


In [8]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [11]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [12]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [13]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [15]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [16]:
arr=np.array([1.5,2.7,3.9])
print(arr.astype(int))

[1 2 3]


In [17]:
# Topic 52  NumPy Indexing, Slicing & Strides
import numpy as np
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [18]:
print(arr[0,1]) # 20 Row 0 column 1
print(arr[2,2]) # 90 Row 2 column 2

20
90


In [19]:
print(arr[-1,-2]) # 80 Last Row 2nd Last Column
print(arr[-3,-3]) # 10 First Row First Column

80
10


In [20]:
# General Form: arr[start:stop:step]
print(arr[0:2,1:3]) # Row 0-1 Column 1-2

[[20 30]
 [50 60]]


In [21]:
print(arr[::2,::2]) # Every 2nd Row and 2nd column

[[10 30]
 [70 90]]


In [22]:
slice_arr=arr[0,:2]
slice_arr[0]=999    # View Not a copy

In [23]:
print(arr[0])  # original changes

[999  20  30]


In [24]:
copy_arr=arr[1].copy() # Independent copy
copy_arr[0]=555

In [25]:
print(arr[1])

[40 50 60]


In [26]:
# Topic 53 NumPy Random Numbers, Reproducibility & Performance Tips
# Simulat 100k coin flips
import numpy as np
# np.random.seed(42)


In [27]:
rng=np.random.default_rng()
flips=rng.integers(0,2,100000)
prob_heads=np.mean(flips)
print("Estimated Probibility of Head: ", prob_heads)

Estimated Probibility of Head:  0.50061


In [28]:
# Simulation with seed
rng=np.random.default_rng(seed=43) # Give us same numbers
flips=rng.integers(0,2,100000)
prob_heads=np.mean(flips)
print("Estimated Probibility of Head: ",prob_heads)

Estimated Probibility of Head:  0.50238


In [29]:
import time
# Python Loop
start_time=time.time()
squares=[i**2 for i in range(1000000)]
end_time=time.time()
print("Python Loop Time:", end_time-start_time)

# Numpy Vectorized
start_time=time.time()
arr=np.arange(1000000)
squares_np=arr**2
end_time=time.time()
print("Numpy Vectorized Time:", end_time-start_time)

Python Loop Time: 0.11046719551086426
Numpy Vectorized Time: 0.009481191635131836


In [30]:
# Topic 54  Pandas Series - Fundamentals
!pip install Pandas

In [31]:
import pandas as pd
# Create a Series
s=pd.Series([10,20,20,30,40], index=['a','b','c','d','e'])
print(s)

a    10
b    20
c    20
d    30
e    40
dtype: int64


In [32]:
# index vs values
print("Values:", s.values)
print("Index:", s.index)
print("Dtype:", s.dtype)
print("Shape:", s.shape)
print("Size:", s.size)
print("Head:", s.head)
print("Tail:", s.tail)


Values: [10 20 20 30 40]
Index: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Dtype: int64
Shape: (5,)
Size: 5
Head: <bound method NDFrame.head of a    10
b    20
c    20
d    30
e    40
dtype: int64>
Tail: <bound method NDFrame.tail of a    10
b    20
c    20
d    30
e    40
dtype: int64>


In [33]:
# Topic 55 Pandas DataFrames - Creation & Inspection
data={
    'Name':['Alice', 'Bob', 'Charlie'],
    'Age':[25,40,30],
    'City':['New York','Paris','London']

}
df=pd.DataFrame(data)
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   40     Paris
2  Charlie   30    London


In [34]:
# Load Sample CSV dataset
import seaborn as sns
# Titanic ka data load karne ke liye
df = sns.load_dataset('titanic')
# Inspect Dataframe
print("Info:\n", df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
Info:
 None


In [35]:
print("\nShape:", df.shape)
print("\nData:", df.dtypes)


Shape: (891, 15)

Data: survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object


In [36]:
print("\nStatistical Summary:\n",df.describe())


Statistical Summary:
          survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200


In [42]:
# Topic 56 Pandas Indexing & Selection - loc & iloc

data={
    'Name':['Alice', 'Bob', 'Charlie','David'],
    'Age':[25,40,30,35],
    'City':['New York','Paris','London','Berlin'],
    'Salary':[40000,50000,60000,45000]

}
df=pd.DataFrame(data)
print("Original DataFrame:\n", data)

Original DataFrame:
 {'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 40, 30, 35], 'City': ['New York', 'Paris', 'London', 'Berlin'], 'Salary': [40000, 50000, 60000, 45000]}


In [47]:
# 1. label base selection (.loc)
subset_loc=df.loc[1:3,['Name','Salary']]
print("Subset With loc:\n",subset_loc)

Subset With loc:
       Name  Salary
1      Bob   50000
2  Charlie   60000
3    David   45000


In [48]:
from re import sub
# Integer Base Selection (.iloc)
subset_iloc=df.iloc[0:2,1:3]
print("Subset With iloc:\n",subset_iloc) # time 4:20

Subset With iloc:
    Age      City
0   25  New York
1   40     Paris
