<a href="https://colab.research.google.com/github/AiWriter404/AI-With-Python-Digiskills/blob/main/AI_With_Python_Digiskills_W3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Topic 48
# What is Data and why its important

In [6]:
# Topic 49
# Introduction of Numpy Seabor and Matplotlib

In [7]:
# Topic 50
# Why Numpy & Enviroment Setup
# pip install numpy
import numpy as np
import time

In [8]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape) # (2,3)
print(arr.ndim)  # 2
print(arr.dtype) # int64 (or Platform dependent)


(2, 3)
2
int64


In [9]:
py_list=list(range(1_000_000))
py_result=[]
start_time=time.time()
for i in py_list:
   py_result.append(i+5)
end_time=time.time()
print("Python List Time:", end_time-start_time)

Python List Time: 0.1284787654876709


In [10]:
np_array=np.arange(1_000_000)
start_time=time.time()
np_result=np_array+5
end_time=time.time()
print("Numpy Array Time:", end_time-start_time)

Numpy Array Time: 0.006730556488037109


In [11]:
# Topic 51
import numpy as np
arr=np.array([1,2,3])
print(arr)


[1 2 3]


In [12]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [15]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [16]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [17]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [19]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [20]:
arr=np.array([1.5,2.7,3.9])
print(arr.astype(int))

[1 2 3]


In [21]:
# Topic 52  NumPy Indexing, Slicing & Strides
import numpy as np
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [22]:
print(arr[0,1]) # 20 Row 0 column 1
print(arr[2,2]) # 90 Row 2 column 2

20
90


In [23]:
print(arr[-1,-2]) # 80 Last Row 2nd Last Column
print(arr[-3,-3]) # 10 First Row First Column

80
10


In [24]:
# General Form: arr[start:stop:step]
print(arr[0:2,1:3]) # Row 0-1 Column 1-2

[[20 30]
 [50 60]]


In [25]:
print(arr[::2,::2]) # Every 2nd Row and 2nd column

[[10 30]
 [70 90]]


In [26]:
slice_arr=arr[0,:2]
slice_arr[0]=999    # View Not a copy

In [27]:
print(arr[0])  # original changes

[999  20  30]


In [28]:
copy_arr=arr[1].copy() # Independent copy
copy_arr[0]=555

In [29]:
print(arr[1])

[40 50 60]


In [33]:
# Topic 53 NumPy Random Numbers, Reproducibility & Performance Tips
# Simulat 100k coin flips
import numpy as np
# np.random.seed(42)


In [43]:
rng=np.random.default_rng()
flips=rng.integers(0,2,100000)
prob_heads=np.mean(flips)
print("Estimated Probibility of Head: ", prob_heads)

Estimated Probibility of Head:  0.49926


In [48]:
# Simulation with seed
rng=np.random.default_rng(seed=43) # Give us same numbers
flips=rng.integers(0,2,100000)
prob_heads=np.mean(flips)
print("Estimated Probibility of Head: ",prob_heads)

Estimated Probibility of Head:  0.50238


In [66]:
import time
# Python Loop
start_time=time.time()
squares=[i**2 for i in range(1000000)]
end_time=time.time()
print("Python Loop Time:", end_time-start_time)

# Numpy Vectorized
start_time=time.time()
arr=np.arange(1000000)
squares_np=arr**2
end_time=time.time()
print("Numpy Vectorized Time:", end_time-start_time)

Python Loop Time: 0.18893027305603027
Numpy Vectorized Time: 0.006186246871948242


In [ ]:
# Topic 54  Pandas Series - Fundamentals